### PR TITLE
[PROG-9] Add LookAhead agent with multiple variations

### PR DESCRIPTION
**Pull request by wrobcio789**
I DO NOT REQUEST A REVIEW YET

image

### CODE REVIEW

**Comment by jakpiase** [comment]
Dear wrobcio789. If you don't want me to review, you can use one of github's features which is "DRAFT" :)

**Comment by wrobcio789** [comment]
> Dear wrobcio789. If you don't want me to review, you can use one of github's features which is "DRAFT" :)
I AM THE UNSTOPPABLE REVIEWERRRRRRRRRRRRRR ONLY DRAFTS CAN STOP ME

**Comment by wrobcio789** [comment]
Needed to update gcc version to 10 in order to support std::ranges

**Review by jakpiase — APPROVED** [review]
LGTM kurde 42 plików mi się nawet sprawdzać nie chce

**Comment by wrobcio789** [comment]
Based on the size of PR it looks like I've rewritten all the repository code and even c++ standard template library

**Comment by wrobcio789** [comment]
LGTM

**Comment by jakpiase** [comment]
@wrobcio789 Could you please help with review? I am actually a little bit busy with writing our engineerka

**Pull request merged**
